/*
 * DialogArco.java
 *
 * Created on November 7, 2007, 8:54 AM
 */

package laboratorio3grafos;

import TDA_Grafo.*;


public class DialogArco extends java.awt.Dialog {
    Grafo<Object> grafo=null;
    /** Creates new form DialogArco */
    public DialogArco(java.awt.Frame parent, boolean modal, Grafo<Object> g) {
        super(parent, modal);
        initComponents();
        grafo = g;
    }
    
    public boolean Aceptar = false;
    public String Vertice1 = "";
    public String Vertice2 = "";
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Adicionar Arco");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        label1.setText("V\u00e9rtice 1:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, -1));

        button1.setLabel("Aceptar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1Aceptar(evt);
            }
        });

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        button2.setLabel("Cancelar");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2Cancelar(evt);
            }
        });

        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, -1));

        label2.setText("V\u00e9rtice 2:");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));

        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2Cancelar
// TODO add your handling code here:
        Aceptar = false;
        Vertice1 = "";
        Vertice2 = "";
        setVisible(false);
    }//GEN-LAST:event_button2Cancelar

    private void button1Aceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1Aceptar
// TODO add your handling code here:
        Aceptar = true;
        if(textField1.getText().trim().length() >0  && textField2.getText().trim().length() >0)
        Vertice1 = textField1.getText().trim();
        Vertice2 = textField2.getText().trim();
        setVisible(false);
    }//GEN-LAST:event_button1Aceptar
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new DialogArco(new java.awt.Frame(), true).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
    
}
