/*
 * DialogVertice.java
 *
 * Created on 7 de noviembre de 2007, 2:18
 */

package laboratorio3grafos;

import TDA_Grafo.*;

public class DialogVertice extends java.awt.Dialog {
    Grafo<Object> grafo=null;
    /** Creates new form DialogVertice */
    public DialogVertice(java.awt.Frame parent, boolean modal, Grafo<Object> g) {
        super(parent, modal);
        initComponents();
         grafo = g;
    }
    
    public boolean Aceptar = false;
    public String Dato = "";
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setResizable(false);
        setTitle("Adicionar V\u00e9rtice");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        label1.setText("Elemento:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, -1));

        button1.setLabel("Aceptar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1Aceptar(evt);
            }
        });

        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        button2.setLabel("Cancelar");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2Cancelar(evt);
            }
        });

        add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 70, -1));

        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2Cancelar
// TODO add your handling code here:
        Aceptar = false;
        Dato = "";
        setVisible(false);
    }//GEN-LAST:event_button2Cancelar

    private void button1Aceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1Aceptar
// TODO add your handling code here:
        Aceptar = true;
        Dato = textField1.getText();
        setVisible(false);
    }//GEN-LAST:event_button1Aceptar
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DialogVertice(new java.awt.Frame(), true).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
    
}
