/*
 * JFrameCPGrafos.java
 *
 * Created on 6 de noviembre de 2007, 0:06
 */

package laboratorio3grafos;

import TDA_Grafo.*;


public class JFrameCPGrafos extends javax.swing.JFrame {
    static Grafo<Object> grafo = null ; 
    /** Creates new form JFrameCPGrafos */
    public JFrameCPGrafos()
    {
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        canvas1.setVisible(false);
        list1.setVisible(false);
       }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        canvas1 = new MyCanvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grafos");
        jLabel1.setText("Matriz de adyacencia");

        jLabel2.setText("Informaci\u00f3n de los v\u00e9rtices");

        jMenu1.setText("Operaciones");
        jMenu2.setText("Crear Grafo");
        jMenuItem4.setText("Grafo No Ponderado con lista de adyacencia");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearNoPonderadoLA(evt);
            }
        });

        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Grafo No Ponderado con matriz de adyacencia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearNoPonderadoMA(evt);
            }
        });

        jMenu2.add(jMenuItem5);

        jMenu1.add(jMenu2);

        jMenu3.setText("Adicionar");
        jMenu3.setEnabled(false);
        jMenuItem2.setText("V\u00e9rtice");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarVertice(evt);
            }
        });

        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Arco");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarArco(evt);
            }
        });

        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu1.add(jSeparator1);

        jMenuItem6.setText("Propiedades");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Propiedades(evt);
            }
        });

        jMenu1.add(jMenuItem6);

        jMenu1.add(jSeparator2);

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(list1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(canvas1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(95, 95, 95)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, canvas1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(list1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Propiedades(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Propiedades
        // TODO add your handling code here:
        new FramePropiedades(grafo).setVisible(true);
    }//GEN-LAST:event_Propiedades

    private void CrearNoPonderadoMA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearNoPonderadoMA
        // TODO add your handling code here:
        list1.removeAll();
        grafo = new GrafoNoPonderadoMA();
        canvas1.setGrafo(grafo);
        jLabel1.setText("Matriz de Adyacencia:");
        Activar();
        invalidate();
    }//GEN-LAST:event_CrearNoPonderadoMA

    private void Cerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Cerrar

    private void CrearNoPonderadoLA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearNoPonderadoLA
        // TODO add your handling code here:
        list1.removeAll();
        grafo = new GrafoNoPonderadoLA();
        canvas1.setGrafo(grafo);
        jLabel1.setText("Lista de Adyacencia:");
        Activar();
        repaint();
    }//GEN-LAST:event_CrearNoPonderadoLA

    private void Activar()
    {
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        canvas1.setVisible(true);
        list1.setVisible(true);
        jMenu3.setEnabled(true);
        jMenuItem2.setEnabled(true);
        jMenuItem3.setEnabled(true);
    }
    
    private void AdicionarArco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarArco
        // TODO add your handling code here:
        DialogArco frame = new DialogArco(this, true,grafo);
        frame.setVisible(true);
        if(frame.Aceptar)
        {
            grafo.InsertarArco(new Arco(frame.Vertice1, frame.Vertice2));
            canvas1.repaint();
        }
        
    }//GEN-LAST:event_AdicionarArco

    private void AdicionarVertice(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarVertice
        // TODO add your handling code here:
        DialogVertice frame = new DialogVertice(this, true,grafo);
        frame.setVisible(true);
        if(frame.Aceptar)
        {
            if(!grafo.EstaElVertice(frame.Dato)){
                grafo.InsertarVertice(frame.Dato);            
                list1.add(grafo.NumeroDeVertices() + " - " + frame.Dato );
                canvas1.repaint();
            }
        }    
    }//GEN-LAST:event_AdicionarVertice
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCPGrafos().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyCanvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
    
}
