/*
 * DialogPeso.java
 *
 * Created on 8 de noviembre de 2006, 17:52
 */

package grafo.gui;

import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author  rolandotr
 */
public class DialogPeso extends javax.swing.JDialog {
    
    /** Creates new form DialogPeso */
    public DialogPeso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Point p = parent.getLocation();
        Dimension d = parent.getSize();
        this.setLocation(d.width/2, d.height/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peso");
        setAlwaysOnTop(true);
        setModal(true);
        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Entre el peso:");
        jPanel2.add(jLabel1);

        tfPeso.setText("1");
        jPanel2.add(tfPeso);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int peso = 1;
    public int getPeso(){
        return peso;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text = tfPeso.getText();
        try{
            peso = (new Integer(text)).intValue();
        }catch (NumberFormatException e){
          JOptionPane.showMessageDialog(this, "Numero con formato incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
          return;
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogPeso(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
    
}
