package grafo.gui;

public class VerticeVisual extends javax.swing.JPanel {
  
  /** Creates new form VerticeVisual */
  public VerticeVisual(int index, String text) {
    if (index <= 0) throw new IllegalArgumentException("index == " + index + " < 0");
    if (text.length() == 0) throw new IllegalArgumentException("text.length() == 0");
    initComponents();
    lbIndex.setText(""+index);
    lbText.setText(text);
    colorBackground = getBackground();
    colorSelected = java.awt.Color.YELLOW;
    //setBorder(javax.swing.BorderFactory.createEtchedBorder());
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbIndex = new javax.swing.JLabel();
        lbText = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(40, 50));
        lbIndex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.01;
        add(lbIndex, gridBagConstraints);

        lbText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.01;
        gridBagConstraints.weighty = 0.01;
        add(lbText, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
  
  public int getIndex() {
    return Integer.parseInt(lbIndex.getText());
  }
  
  public String getText() {
    return lbText.getText();
  }
  
  public void setSelected(boolean selected) {
    this.selected = selected;
    setBackground(selected ? colorSelected : colorBackground);
  }
  
  public boolean isSelected() {
    return selected;
  }
  
  private boolean selected = false;
  private java.awt.Color colorBackground, colorSelected;
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIndex;
    private javax.swing.JLabel lbText;
    // End of variables declaration//GEN-END:variables
  
}
