/*
 * JDialogIndicaciones.java
 *
 * Created on 22 de octubre de 2006, 16:19
 */

package arbolesbinarios;

/**
 *
 * @author  lester
 */
public class JDialogIndicaciones extends javax.swing.JDialog {
    
    /** Creates new form JDialogIndicaciones */
    public JDialogIndicaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indicaciones");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Indicaciones generales:");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText(" Para realizar los ejercicios hemos creado una estructura de clases y m\u00e9todos implementados  que\npueden ser utilizados por usted. Estudie la aplicaci\u00f3n detenidamente antes de comenzar.  \n\nEst\u00e1n implementados varios m\u00e9todos importantes que pueden ser de su utilidad.  En cada\nejercicio le daremos una referencia al principio de cada ActionPerformed, que usted tiene que \nimplementar,  a la clase JTreeVisual, la cual contiene entre otros los m\u00e9todos:      \n\npublic IArbolBinario<String> getArbol(); // Devuelve el \u00e1rbol ra\u00edz de todos los sub\u00e1rboles.    \n\npublic IArbolBinario<String> getArbolActual(); // Devuelve el sub\u00e1rbol actual que estamos viendo \n                                                                           // en la aplicaci\u00f3n.     \n\nEstos m\u00e9todos son los que com\u00fanmente van a ser utilizados por usted. Obteniendo un \u00e1rbol o \nsub\u00e1rbol (que es tambi\u00e9n un \u00e1rbol). Entonces se puede aplicar cualquiera de los m\u00e9todos del TDA \n\u00e1rbol ya visto en conferencia y clase pr\u00e1ctica.\n\nNota aclaratoria, para todos los ejercicios: \n\nEn caso de no encontrar lo especificado, se deber\u00e1 devolver en los jLabelResultado el String \n\u201cNo encontrado\u201d. ");
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Aceptar");
        jButton1.setToolTipText("\nPara realizar los ejercicios hemos creado una estructura de clases y m\u00e9todos implementados \nque pueden ser utilizados por usted. Estudie la aplicaci\u00f3n detenidamente antes de comenzar. \n\nEst\u00e1n implementados varios m\u00e9todos importantes que pueden ser de su utilidad.  En cada ejercicio\nle daremos una referencia al principio de cada ActionPerformed, que usted tiene que implementar, \na la clase JTreeVisual, la cual contiene entre otros los m\u00e9todos:    \n\n\npublic IArbolBinario<String> getArbol(); // Devuelve el \u00e1rbol ra\u00edz de todos los sub\u00e1rboles.  \n\npublic IArbolBinario<String> getArbolActual(); // Devuelve el sub\u00e1rbol actual que estamos viendo en la\n                                                                                  // aplicaci\u00f3n.  \n\n\nEstos m\u00e9todos son los que com\u00fanmente van a ser utilizados por usted. Obteniendo un \u00e1rbol o\nsub\u00e1rbol (que es tambi\u00e9n un \u00e1rbol). Entonces se puede aplicar cualquiera de los m\u00e9todos del TDA \n\u00e1rbol ya visto en conferencia y clase pr\u00e1ctica.  Nota aclaratoria, para todos los ejercicios: En caso de\nno encontrar lo especificado, se deber\u00e1 devolver en los jLabelResultado el String \u201cNo encontrado\u201d. ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(246, 246, 246)
                        .add(jButton1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 351, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void initText() {
        jTextArea1.setColumns(100);
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
